export * from './auth';
export * from './academic';
export * from './staff';
export * from './finance';
export * from './campus';
export * from './communication';
export * from './medical';
export * from './cafeteria';
export * from './common';
